version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: apps/excelidraw-frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_WS_URL
    depends_on:
      - http-backend
      - websocket-backend

  http-backend:
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - FRONTEND_URL

  websocket-backend:
    build:
      context: .
      dockerfile: apps/websocket-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL
      - JWT_SECRET